-- Daily brief tasks are auto-generated by the cron job. Distinguishing them
-- from manual tasks keeps the source column useful (icons, filters later).

alter table public.tasks
  drop constraint tasks_source_check;

alter table public.tasks
  add constraint tasks_source_check
  check (source in (
    'manual',
    'brief',
    'gmail',
    'calendar',
    'slack',
    'jira',
    'clickup'
  ));
